name: Base CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        id: echo-text
        run: |
          echo "url=https://blog.mooriii.com" >> $GITHUB_OUTPUT
          echo "url2=$(echo "https://blog.mooriii.com" | sed -e 's|https://||')" >> $GITHUB_OUTPUT
      - name: Debug Output
        run: echo "Extracted URL ${{ steps.echo-text.outputs.url }}"
      - name: Debug Output2
        run: echo "Extracted URL ${{ steps.echo-text.outputs.url2 }}"

